config/routes.rb
Swap::Application.routes.draw do
  resources :event_invitations

  resources :groups

  post 'invitations', to: :invite_user, controller: :devise_users, as: :invitation_to_group

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: :get
  
  root :to => 'events#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  get 'users/:id/groups/' => 'users#groups', as: "my_groups"
  resources :events
end

app/models/group.rb
class Group < ActiveRecord::Base 
	has_many :group_members, :dependent => :destroy
	has_many :users, :through => :group_members
	belongs_to  :owner, class_name: User, foreign_key: :owner_id

	def self.send_invitations(invitees)
		addresses = invitees.split(/\s*[,;]\s* # comma or semicolon, optionally surrounded by whitespace
      | \s{1,}      # two or more whitespace characters
      | [\r\n]+     # any number of newline characters
      /x) unless invitees.nil?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def invite_members
    @invites = Group.send_invitations(params[:invitees])
    @invites.each do |invitee|
      User.invite!(:email => invitee)
    end
  end
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.users << current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
      current_group = @group
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name, :owner_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def current_group=(group)
    @current_group = group
  end
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :group_name %>
    <%= f.hidden_field :owner_id, value: current_user.id %>
  </div>
 </br>
  <div>
    <%= f.button :submit, :class => 'btn-primary'  %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Group name</th>
      <th>Owned by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= group.owner.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @group.group_name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @group.owner.name %>
</p>
<p>
<% unless @group.users.count == 0 %>
  <strong>Members:</strong>
  <% @group.users.each do |member| %>
  	<%= member.name %>
  <% end %>
<% end %>
</p>
<p> <%= link_to 'Invite a Friend', invitation_to_group_path %> <p>
<p>
	<%= form_tag invite_members_to_groups_path, :method => :post do %>
  	<%= label_tag "Would you like to invite more friends?" %> </br>
  	<%= label_tag "Enter their email addresses separated by a comma (or one on each line)." %> </br>
  	<%= text_area_tag :invitees %>
  	<%= submit_tag "Invite My Friends!" %>
<% end %>
</p>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>