config/routes.rb
Swap::Application.routes.draw do
  resources :event_invitations

  resources :groups

  post 'invitations', to: :invite_user, controller: :devise_users, as: :invitation_to_group

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}, via: :get
  
  root :to => 'events#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  get 'users/:id/groups/' => 'users#groups', as: "my_groups"
  resources :events
end

app/models/event_invitation.rb
class EventInvitation < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :owner, class_name: User, foreign_key: :invite_sent_by

  def lookup_emails(emails)
    emails.each do |email|
      if Users.where(email: :email)
        #send the event_invitation
      else
        #send the devise/website invitation
      end
    end
  end

  def self.split_addresses(invitees)
    addresses = invitees.split(/\s*[,;]\s* # comma or semicolon, optionally surrounded by whitespace
      | \s{1,}      # two or more whitespace characters
      | [\r\n]+     # any number of newline characters
      /x) unless invitees.nil?
  end
end

app/controllers/event_invitations_controller.rb
class EventInvitationsController < ApplicationController
  before_action :set_event_invitation, only: [:show, :edit, :update, :destroy]

  # GET /event_invitations
  # GET /event_invitations.json
  def index
    @event_invitations = EventInvitation.all
  end

  # GET /event_invitations/1
  # GET /event_invitations/1.json
  def show
  end

  # GET /event_invitations/new
  def new
    @event = Event.new
    @event.event_invitations.build
  end

  # GET /event_invitations/1/edit
  def edit
  end

  # POST /event_invitations
  # POST /event_invitations.json
  def create
    msg = event_invitation_params[:email_message]
    emails = EventInvitation.lookup_emails(EventInviation.split_addresses(event_invitation_params[:user_emails]))
    
    @event_invitation = EventInvitation.new(event_invitation_params)

    respond_to do |format|
      if @event_invitation.save
        format.html { redirect_to @event_invitation, notice: 'Event invitation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event_invitation }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_invitations/1
  # PATCH/PUT /event_invitations/1.json
  def update
    respond_to do |format|
      if @event_invitation.update(event_invitation_params)
        format.html { redirect_to @event_invitation, notice: 'Event invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_invitations/1
  # DELETE /event_invitations/1.json
  def destroy
    @event_invitation.destroy
    respond_to do |format|
      format.html { redirect_to event_invitations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_invitation
      @event_invitation = EventInvitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_invitation_params
      params.require(:event_invitation).permit(:invite_sent_by, :invite_sent_to, :user_emails, :email_message)
    end
end

app/helpers/event_invitations_helper.rb
module EventInvitationsHelper
end

app/views/event_invitations/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= form_tag event_invitations_path, :method => :post do %>
  	<%= label_tag "Email ids of people you'd like to invite." %>
  </div><div>
  	<%= text_area_tag :user_emails %>
  </div><div>
  	<%= label_tag "Your message:" %>
  </div><div>
  	<%= text_area_tag :email_message %>
	<% end %>
  </div>

  <div class="form-actions">
  		<%= submit_tag "Invite!", :class => "btn-primary"  %>
  </div>
<% end %>

app/views/event_invitations/edit.html.erb
<h1>Editing event_invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_invitation %> |
<%= link_to 'Back', event_invitations_path %>

app/views/event_invitations/index.html.erb
<h1>Listing event_invitations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_invitations.each do |event_invitation| %>
      <tr>
        <td><%= link_to 'Show', event_invitation %></td>
        <td><%= link_to 'Edit', edit_event_invitation_path(event_invitation) %></td>
        <td><%= link_to 'Destroy', event_invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event invitation', new_event_invitation_path %>

app/views/event_invitations/new.html.erb
<h1>Find a Sitter!</h1>

<%= render 'events/form' %>

<%= render 'form' %>

<%= link_to 'Back', event_invitations_path %>

app/views/event_invitations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_invitation_path(@event_invitation) %> |
<%= link_to 'Back', event_invitations_path %>